### ISSUE TITLE
ApiCalendar any type

### ISSUE THREAD

**Issue by Hjkun77** [Kubessandra/react-google-calendar-api#46]
Variable 'ApiCalendar' implicitly has type 'any' in some locations where its type cannot be determined.ts(7034)

**Comment by pedrorossato** [comment]
same here

**Comment by Kubessandra** [comment]
What is your import?

**Comment by Hjkun77** [comment]
The one stated in the README.md for typescript @Kubessandra

**Comment by Kubessandra** [comment]
If you try adding .ts for the extension of the import does it work?

**Comment by pedrorossato** [comment]
> If you try adding .ts for the extension of the import does it work?
You mean `import ApiCalendar from 'react-google-calendar-api/src/ApiCalendar.ts';`?
If so, doesn't work...

**Comment by Hjkun77** [comment]
Yep adding `.ts` doesn't work as well.

The types any in the dependency is throwing an error.

**Comment by kaiserkaran018** [comment]
> Yep adding `.ts` doesn't work as well.
> 
> The types any in the dependency is throwing an error.

Yes It's not working....

**Comment by ravishwetha** [comment]
<img width="805" alt="Screenshot 2022-04-20 at 12 13 02 PM" src="https://user-images.githubusercontent.com/18163420/164149017-9c70bfed-4db9-4f00-ba22-e12e4909cfc2.png">

This is the compile error received:

Compiled with problems:X

ERROR in node_modules/react-google-calendar-api/src/ApiCalendar.ts:44:24

TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.
    42 |    */
    43 |   private initClient(): void {
  > 44 |     this.gapi = window['gapi'];
       |                        ^^^^^^
    45 |     this.gapi.client
    46 |       .init(Config)
    47 |       .then(() => {


ERROR in node_modules/react-google-calendar-api/src/ApiCalendar.ts:70:24

TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.
    68 |    */
    69 |   private handleClientLoad(): void {
  > 70 |     this.gapi = window['gapi'];
       |                        ^^^^^^
    71 |     const script = document.createElement('script');
    72 |     script.src = 'https://apis.google.com/js/api.js';
    73 |     document.body.appendChild(script);


ERROR in node_modules/react-google-calendar-api/src/ApiCalendar.ts:75:14

TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.
    73 |     document.body.appendChild(script);
    74 |     script.onload = (): void => {
  > 75 |       window['gapi'].load('client:auth2', this.initClient);
       |              ^^^^^^
    76 |     };
    77 |   }
    78 |

**Comment by Kubessandra** [comment]
Hi,
This has been fixed [commit](https://github.com/Kubessandra/react-google-calendar-api/commit/1a28b616da788bde8fa8ad78e43e733233c3b06b) version [> 2.0.x]

This include a lot of changes if you have any feedbacks / questions do not hesitate
